### PR TITLE
Dockerfile: Add missing x11 packages

### PR DESCRIPTION
**Pull request by SanchayanMaity**
Add the missing x11 packages required for build.

Signed-off-by: Sanchayan Maity <maitysanchayan@gmail.com>

### CODE REVIEW

**Comment by cbrake** [comment]
I'm curious -- what failures did you see that required the x11 packages?

**Comment by cbrake** [comment]
also, you may be interested in https://github.com/YoeDistro/yoe-distro -- that is where new development on the oe-build template is happening.

**Comment by SanchayanMaity** [comment]
Sorry for missing up on that information. I was using your [oe-build](https://github.com/cbrake/oe-build) template with some modifications with this docker image. Used poky instead of openembedded-core and a different set of layers for building an image for the Xilinx Ultrascale MPSoC. For the build, it asked for the xvfb and the xlsclients package, so I had to add these. Thanks for pointing me to the new oe-build template repo.

**Comment by cbrake** [comment]
no problem -- I'm glad to add stuff that makes the container more generally useful.

**Pull request merged**
